# Generated by Django 4.2.16 on 2024-11-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='tablestatus',
            field=models.CharField(choices=[('occupied', 'Occupied'), ('reserved', 'Reserved')], max_length=20),
        ),
    ]
