# Generated by Django 4.2.16 on 2024-11-05 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribeapp', '0003_table_amount_table_extra_allowances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='amount',
            field=models.PositiveIntegerField(default=0, help_text='Enter an amount between 0 and 1000', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='table',
            name='extra_allowances',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Ciggrates'),
        ),
    ]
