# Generated by Django 4.2.16 on 2024-11-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tribeapp', '0004_alter_table_amount_alter_table_extra_allowances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='tablenumber',
        ),
    ]
