# Generated by Django 4.2.16 on 2024-11-05 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribeapp', '0006_alter_table_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='amount',
            field=models.PositiveIntegerField(default=100, help_text='Enter an amount between 0 and 1000', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
