# Generated by Django 4.2.16 on 2024-11-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribeapp', '0008_alter_table_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Enter an Time between 00:00 and 23:59', null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='start_timing',
            field=models.TimeField(blank=True, help_text='Enter an Time between 00:00 and 23:59', null=True),
        ),
    ]
