# Generated by Django 4.2.16 on 2024-11-06 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribeapp', '0009_alter_table_end_time_alter_table_start_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='extra_allowances',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Extra Charges'),
        ),
    ]
