# Generated by Django 4.2.16 on 2024-11-06 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribeapp', '0010_alter_table_extra_allowances'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 10, 0, 0, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
